### ISSUE TITLE
JSON Exporter Formatting Issue

### ISSUE THREAD

**Issue by butchersoft1** [Norconex/committer-core#18] opened 2018-12-18 04:10 UTC
When exporting records using the JSON not property formatted

                <committer class="com.norconex.committer.core.impl.JSONFileCommitter">
                    <directory>${workdir}/json</directory>
                    <pretty>false</pretty>
                    <docsPerFile>500</docsPerFile>
                    <compress>true</compress>
                    <splitAddDelete>true</splitAddDelete>
                    <fileNamePrefix>js</fileNamePrefix>
                    <fileNameSuffix></fileNameSuffix>
                </committer>

the metadata field is not formatted as JSON but as an "ObservableMap " object 

**Example**
"metadata": "ObservableMap [map=ObservableMap [map=ObservableMap [map={dacl=[public, everyone], title=[This looks like the title], modified=[2018-12-09]

**Comment by essiembre** [comment] 2018-12-25 16:52
A new Committer Core [snapshot release](http://www.norconex.com/collectors/committer-core/download) was just made with a fix for this.  Please give it a try and confirm.

**Comment by butchersoft1** [comment] 2019-01-03 02:39
Thanks,  sorry for the delay in response, Christmas break.   Ran a quick test today and the metadata field is now correctly parsing into JSON

**Comment by essiembre** [comment] 2019-01-03 03:49
Great. Thanks for confirming.

**Closed by essiembre** 2019-01-03 03:49 UTC
Labels: bug, fixed/done

**Comment by butchersoft1** [comment] 2020-02-12 08:12
Hello essiembre,   

I had to upgrade to take advantage of some of your new features including limiting the length of text fields.

This issue appears to have returned - tested on 2.8 and latest 2.91 snapshots

Yours Butchersoft

**Comment by essiembre** [comment] 2020-02-17 21:11
I am not able to reproduce the issue.  Can you confirm in your lib directory you have the latest committer-core version?  It should be 2.1.3.  Also verify you have norconex-commons-lang 1.15.1.   Make sure you have no duplicate jar versions.

**Comment by butchersoft1** [comment] 2020-03-01 22:16
Hello Essiembre,

Thanks for the file check - I could see the following which does appear to show duplicates

09/20/2019  02:36 PM           199,692 norconex-collector-core-1.10.0-SNAPSHOT.jar
09/20/2019  02:41 PM           399,632 norconex-collector-http-2.9.0-SNAPSHOT.jar
01/09/2018  09:12 PM            16,875 norconex-committer-azuresearch-1.1.1.jar
_12/18/2017  11:17 PM            59,767 norconex-committer-core-2.1.2.jar_
01/05/2019  06:36 PM            59,815 norconex-committer-core-2.1.3-SNAPSHOT.jar
_12/13/2017  12:06 AM           239,943 norconex-commons-lang-1.14.0.jar_
07/29/2019  05:42 PM           244,011 norconex-commons-lang-1.15.1-SNAPSHOT.jar
07/03/2019  12:27 AM           527,217 norconex-importer-2.10.0-SNAPSHOT.jar
09/20/2019  02:32 PM            94,620 norconex-jef-4.1.2-SNAPSHOT.jar

I removed the items in Italic and this has resolved the problem

Thanks you
